name: Package and release

on:
  push:
    tags:
      - "**"

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release for TBCC
        uses: BigWigsMods/packager@v1
        with:
          args: -g bcc -p 492599
